#!/bin/bash
#SBATCH -J job_name								                            #Job name
#SBATCH -o /path/to/directory/job_name.o%j		                            #Output file name
#SBATCH -e /path/to/directory/job_name.%N.%j.err	                        #Output error file
#SBATCH --nodes=1								                            #Number of nodes
#SBATCH --ntasks=1								                            #Number of tasks
#SBATCH --cpus-per-task=1							                        #Number of cores available per task
#SBATCH -p normal								                            #SLURM queue (partition)
#SBATCH --array=a-b								                            #How many jobs in parallel (eg. 1-3 for three jobs)
#SBATCH -t hh:mm:ss								                            #run time (hh:mm:ss)

echo $SLURM_JOB_ID
echo $SLURM_JOB_NAME
echo $SLURM_JOB_NUM_NODES

UNMERGED_DIRECTORY="/path/to/working/directory/"
MERGED_DIRECTORY="/path/to/working/directory/"

#Script:
L1ID="_L001"                #Set the laneID     (eg. L001)
filetype=".fastq.gz"        #Set                (eg. .fastq.gz)
                            #Important to include .  ^ 
for f in *"${L1ID}"*; do
    base="${f%${L1ID}*}"
    echo "Merging $base"
    cat $base* > "$MERGED_DIR/$base.merged$filetype"
done
