#!/bin/bash
#SBATCH -J merge_fastq						                                                #Job name
#SBATCH -o /path/to/Bioinfo-pipeline-automatization/SLURM/Merge_logs/Merge_fastq.o%j		#Output file name
#SBATCH -e /path/to/Bioinfo-pipeline-automatization/SLURM/Merge_logs/Merge_fastq.%N.%j.err	#Output error file
#SBATCH --nodes=1								                                            #Number of nodes
#SBATCH --ntasks=1  					                                                    #Number of tasks
#SBATCH --cpus-per-task=1					                                                #Number of cores available per task
#SBATCH -p normal						                                                    #SLURM queue (partition)
#SBATCH --array=1-n%x 					                                                    #Process n files with a max of x ran in parallel
#SBATCH -t 00:00:20						                                                    #run time (hh:mm:ss)

echo $SLURM_JOB_ID
echo $SLURM_JOB_NAME
echo $SLURM_JOB_NUM_NODES

REPO_DIR="/path/to/Bioinfo-pipeline-automatization"                             #Change the first // to match repo path
UNMERGED_DIRECTORY="${REPO_DIR}/Samples/unmerged"
MERGED_DIRECTORY="${REPO_DIR}/Samples/merged" 
BASE="$(sed "${SLURM_ARRAY_TASK_ID}q;d" ${UNMERGED_DIRECTORY}/file.txt)"        #$file must be a .txt file with all sample base names
#Script:

echo "Merging ${BASE} test"
cat ${UNMERGED_DIRECTORY}/${BASE}* > "${MERGED_DIRECTORY}/${BASE}.merged.fastq.gz"