#!/bin/bash
#SBATCH -J miRNA_pipeline								                    #Job name
#SBATCH -o /path/to/directory/miRNA_pipeline.o%j		                    #Output file name
#SBATCH -e /path/to/directory/miRNA_pipeline.%N.%j.err	                    #Output error file
#SBATCH --nodes=1								                            #Number of nodes
#SBATCH --ntasks=1								                            #Number of tasks
#SBATCH --cpus-per-task=1							                        #Number of cores available per task
#SBATCH -p normal								                            #SLURM queue (partition)
#SBATCH --array=1-3								                            #How many jobs in parallel (3 this time)
#SBATCH -t 02:00:00								                            #run time (hh:mm:ss)

echo $SLURM_JOB_ID
echo $SLURM_JOB_NAME
echo $SLURM_JOB_NUM_NODES

# ============================================================
# Declare absolute paths to environment tools
# ============================================================
BOWTIE="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/bowtie"
SAMTOOLS="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/samtools"
UMI_TOOLS="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/umi_tools"
FASTP="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/fastp"
WORKING_DIRECTORY="/path/to/working/directory/" # Absolute path to directory that will store results. Path must have the "/" at the end!

#File with all sample names must be created before hand
SAMPLE="${WORKING_DIRECTORY}$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${WORKING_DIRECTORY}samples.txt")" 

BASE=$(basename "$SAMPLE" .fastq)
PREFIX="${WORKING_DIRECTORY}${BASE}"

#Bowtie reference must be created beforehand using "bowtie-build <reference.fa> <index_reference_name>"
REFERENCE="/path/to/directory_with_ebwt_files/index_reference_name"

"$UMI_TOOLS" extract --extract-method=regex --bc-pattern='.+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12})(?P<discard_2>.*)$' -I "${PREFIX}.fastq" -S "${PREFIX}_umiextracted.fastq"

"$FASTP" -i "${PREFIX}_umiextracted.fastq" -o "${PREFIX}_filtered.fastq" -l 17

"$BOWTIE" -p 1 -q -S "${REFERENCE}" "${PREFIX}_filtered.fastq" > "${PREFIX}.sam"

"$SAMTOOLS" view -bS "${PREFIX}.sam" | "$SAMTOOLS" sort -@ 1 -o "${PREFIX}.sorted.bam"

"$SAMTOOLS" index "${PREFIX}.sorted.bam"

"$UMI_TOOLS" dedup --method=unique --stdin="${PREFIX}.sorted.bam" --stdout="${PREFIX}.sorted.dedup.bam"

"$SAMTOOLS" index "${PREFIX}.sorted.dedup.bam"

(echo "Reference,Length,Mapped,Unmapped"; "$SAMTOOLS" idxstats "${PREFIX}.sorted.dedup.bam" | tr '\t' ',') > "${PREFIX}.dedup.idxstats.csv"
