#!/bin/bash
#SBATCH -J miRNA_pipeline								                    #Job name
#SBATCH -o /path/to/directory/Bioinfo-pipeline-automatization/SLURM/logs_pipeline/pipeline.o%j		                    #Output file name
#SBATCH -e /path/to/directory/Bioinfo-pipeline-automatization/SLURM/logs_pipeline/pipeline.%N.%j.err	                    #Output error file
#SBATCH --nodes=1								                            #Number of nodes
#SBATCH --ntasks=1								                            #Number of tasks
#SBATCH --cpus-per-task=1							                        #Number of cores available per task
#SBATCH -p normal								                            #SLURM queue (partition)
#SBATCH --array=1-3								                            #How many jobs in parallel (3 this time)
#SBATCH -t 02:00:00								                            #run time (hh:mm:ss)

echo $SLURM_JOB_ID
echo $SLURM_JOB_NAME
echo $SLURM_JOB_NUM_NODES

# ============================================================
# Declare absolute path repo directory
# ============================================================

# Must include the last "/" otherwise pipeline wont work !!!
WORKING_DIRECTORY="/path/to/Bioinfo-pipeline-automatization/"

# Bowtie reference must be created beforehand using "bowtie-build <reference.fa> <index_reference_name>"
# You can run Reference/get_reference to automatically download miRNAs from miRBase and MirGeneDB
REFERENCE="${WORKING_DIRECTORY}Reference/index_reference_name"

# ============================================================
# Declare absolute paths to environment tools
# ============================================================

BOWTIE="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/bowtie"
SAMTOOLS="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/samtools"
UMI_TOOLS="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/umi_tools"
FASTP="/path/to/micromamba/envs/ENVIRONMENT_NAME/bin/fastp"

# ============================================================
# Declare variables
# ============================================================

# File with all sample names must be created before hand (e.g. in Samples/samplesheet.txt)
# Write full sample name without path and with file type

# ~~~~~!! IMPORTANT: samples in samplesheet.txt must exist in Samples/merged !!~~~~~
SAMPLE="${WORKING_DIRECTORY}Samples/merged/$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${WORKING_DIRECTORY}Samples/samplesheet.txt")" 

# Get sample basename to tag every output of the pipeline
BASE=$(basename "$SAMPLE")
BASE=${BASE%.gz}
BASE=${BASE%.fastq}

# Create directory for pipeline outputs
SAMPLE_DIR="${WORKING_DIRECTORY}SLURM/logs_merge/pipeline.${SLURM_JOB_ID}.${BASE}"
mkdir -p "${SAMPLE_DIR}"
PREFIX="${SAMPLE_DIR}/${BASE}"

# ============================================================
# Pipeline
# ============================================================

"$UMI_TOOLS" extract \
    --extract-method=regex \
    --bc-pattern='.+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12})(?P<discard_2>.*)$' \
    -I "${PREFIX}.fastq" \
    -S "${PREFIX}_umiextracted.fastq"

"$FASTP" -i "${PREFIX}_umiextracted.fastq" \
    -o "${PREFIX}_filtered.fastq" \
    -l 17 \
    --json "${PREFIX}_fastp.json" \
    --html "${PREFIX}_fastp.html"

"$BOWTIE" -p 1 -q -S "${REFERENCE}" "${PREFIX}_filtered.fastq" > "${PREFIX}.sam"

"$SAMTOOLS" view -bS "${PREFIX}.sam" | "$SAMTOOLS" sort -@ 1 -o "${PREFIX}.sorted.bam"

"$SAMTOOLS" index "${PREFIX}.sorted.bam"

"$UMI_TOOLS" dedup --method=unique --stdin="${PREFIX}.sorted.bam" --stdout="${PREFIX}.sorted.dedup.bam"

"$SAMTOOLS" index "${PREFIX}.sorted.dedup.bam"

(echo "Reference,Length,Mapped,Unmapped"; "$SAMTOOLS" idxstats "${PREFIX}.sorted.dedup.bam" | tr '\t' ',') > "${PREFIX}.dedup.idxstats.csv"
